# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Todo'), (1, 'Done')], default=0),
        ),
    ]
