# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_report_update_20170114_0118'),
        ('support', '0002_helpcenter'),
    ]

    operations = [
    ]
