# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleApproveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sale_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleOffer')),
            ],
        ),
        migrations.CreateModel(
            name='SalePaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
                ('stripe_amount', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sale_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleOffer')),
            ],
        ),
    ]
