# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_saleapproveevent_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='coastal_dollar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='currency',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='currency_rate',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='price_usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
