# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20170114_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='status',
            field=models.CharField(choices=[('request', 'Unconfirmed'), ('approved', 'Approved'), ('declined', 'Declined'), ('invalid', 'Invalid'), ('charge', 'Unpaid'), ('pay', 'In Transaction'), ('finished', 'Finished')], max_length=32),
        ),
    ]
