# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20170120_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='offer_succeed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
