# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def init_categories(apps, schema_editor):
    Category = apps.get_model("product", "Category")

    categories = (
        # (id, path, depth, numchild, name, full_name)
        (1, '0001', 1, 3, "Space", "Space"),
        (2, '0002', 1, 2, "Yacht", "Yacht"),
        (3, '0003', 1, 0, "Jet", "Jet"),
        (4, '00010001', 2, 0, "House", "Space > House"),
        (5, '00010002', 2, 0, "Apartment", "Space > Apartment"),
        (6, '00010003', 2, 0, "Room", "Space > Room"),
        (7, '00020001', 2, 0, "Yacht", "Yacht > Yacht"),
        (8, '00020002', 2, 0, "Boat Slip", "Yacht > Boat Slip"),
    )

    for cid, path, depth, numchild, name, full_name in categories:
        Category.objects.create(id=cid, path=path, depth=depth, numchild=numchild,
                                name=name, full_name=full_name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(db_index=True, editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['full_name'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(init_categories),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('max_guests', models.PositiveSmallIntegerField()),
                ('beds', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('sleeps', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('for_rental', models.BooleanField()),
                ('for_sale', models.BooleanField()),
                ('rental_price', models.FloatField(help_text='here is the price per day')),
                ('rental_usd_price', models.FloatField(editable=False, verbose_name='Rental USD Price')),
                ('rental_unit', models.PositiveSmallIntegerField(choices=[(1, 'Day'), (2, 'Week'), (3, 'Month')])),
            ],
        ),
        migrations.CreateModel(
            name='Jet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
            ],
            bases=('product.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
