# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lon',
        ),
        migrations.AddField(
            model_name='product',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(-118.7730763 34.4648802)', srid=4326),
        ),
    ]
