# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 08:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_add_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_usd_price',
            field=models.FloatField(verbose_name='Rental USD Price'),
        ),
    ]
