# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20161211_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('rental_true', 'direct_rental_true'), ('rental_false', 'direct_rental_false')], help_text='Who can book instantly', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('half-day', 'Half-Day'), ('hour', 'Hour')], max_length=32, null=True),
        ),
    ]
