# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_add_favorites_and_recently_viewed'),
        ('product', '0004_add_rentaldaterange'),
        ('product', '0008_auto_20161212_2214'),
    ]

    operations = [
    ]
