# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_merge_20161213_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favouriteproduct',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('meet-cr', "Guests who meet Coastal's requirements"), ('no-one', 'No one. I will read and approve every request within 24 hours')], help_text='Who can book instantly', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='FavouriteProduct',
        ),
    ]
