# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:04
from __future__ import unicode_literals

from django.db import migrations


def update_category(apps, schema_editor):
    Category = apps.get_model("product", "Category")

    categories = (
        (7, '00020001', 2, 0, "Yacht", "Yacht > Yacht"),
        (8, '00020002', 2, 0, "Boat Slip", "Yacht > Boat Slip"),
    )

    for cid, path, depth, numchild, name, full_name in categories:
        Category.objects.create(id=cid, path=path, depth=depth, numchild=numchild,
                                name=name, full_name=full_name)

    yacht = Category.objects.get(path='0002')
    yacht.numchild = 2
    yacht.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20161213_0054'),
    ]

    operations = [
        migrations.RunPython(update_category),
    ]
