# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20161213_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='product',
            name='viewer',
        ),
        migrations.AlterField(
            model_name='product',
            name='amenities',
            field=models.ManyToManyField(to='product.Amenity'),
        ),
    ]
