# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20161213_1835'),
        ('product', '0011_api_products_form'),
    ]

    operations = [
    ]
