# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20161213_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productviewcount',
            old_name='view_count',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='productviewcount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
