# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20161213_2334'),
        ('product', '0014_add_amenities'),
    ]

    operations = [
    ]
