# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_merge_20161214_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('common', 'Most common'), ('extra', 'Extras'), ('special', 'Special')], default='common', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='product.Amenity'),
        ),
    ]
