# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
