# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_add_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, choices=[('', '----'), ('360-view', '360 View')], default='null', max_length=32),
            preserve_default=False,
        ),
    ]
