# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20161217_2236'),
        ('product', '0020_update_model_sale_price'),
    ]

    operations = [
    ]
