# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_rename_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='id_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
