# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_merge_20161221_0155'),
        ('product', '0024_productimage_id_product'),
    ]

    operations = [
    ]
