# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_merge_20161221_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='id_product',
        ),
    ]
