# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20161222_0457'),
        ('product', '0026_remove_productimage_id_product'),
    ]

    operations = [
    ]
