# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20161222_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rental_currency',
            new_name='currency',
        ),
    ]
