# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_update_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amenities',
            field=models.ManyToManyField(to='product.Amenity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('half-day', 'Half-Day'), ('hour', 'Hour')], max_length=32),
        ),
    ]
