# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20161224_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc_about_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_getting_around',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_guest_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_interaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_other_to_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
