# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20161225_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='product.Amenity'),
        ),
    ]
