# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20161229_0716'),
        ('product', '0033_add_product_timezone'),
    ]

    operations = [
    ]
