# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_merge_20170104_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
