# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 06:45
from __future__ import unicode_literals

from django.db import migrations
from timezonefinder import TimezoneFinder


def add_timezone_product(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    product_list = Product.objects.all()
    for product in product_list:
        if product.point:
            tf = TimezoneFinder()
            product.timezone = tf.timezone_at(lng=product.point[0], lat=product.point[1])
        else:
            product.status = 'draft'
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20170105_2234'),
    ]

    operations = [
        migrations.RunPython(add_timezone_product),
    ]
