# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
