# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
