# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20170110_2355'),
        ('product', '0040_product_rank'),
    ]

    operations = [
    ]
