# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_merge_20170111_2248'),
        ('product', '0041_product_reported'),
    ]

    operations = [
    ]
