# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_merge_20170112_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reported',
        ),
    ]
