# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_remove_product_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distance_from_coastal',
            field=models.FloatField(blank=True, max_length=32, null=True),
        ),
    ]
