# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_product_update_distance_from_coastal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distance_from_coastal',
            field=models.FloatField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
