# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 06:33
from __future__ import unicode_literals

from django.db import migrations


def update_max_guests(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    product_list = Product.objects.all()
    for product in product_list:
        if product.max_guests > 16:
            product.max_guests = 16
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_update_category_experience'),
    ]

    operations = [
        migrations.RunPython(update_max_guests)
    ]
