# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20170228_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City v1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
