# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20170315_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('', '----'), ('360-view', '360 View')], max_length=32),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
