# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 07:40
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20170315_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='caption',
            new_name='image_type',
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
