# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('promotion', '0001_initial'),
        ('promotion', '0002_auto_20161222_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['display_order']},
        ),
    ]
