# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20170125_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='country',
            field=models.CharField(blank=True, help_text='the address field is used for product search', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='county',
            field=models.CharField(blank=True, help_text='the address field is used for product search', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='locality',
            field=models.CharField(blank=True, help_text='the address field is used for product search', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='state',
            field=models.CharField(blank=True, help_text='the address field is used for product search', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='sublocality',
            field=models.CharField(blank=True, help_text='the address field is used for product search', max_length=100, null=True),
        ),
    ]
