# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agency_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency_email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
