# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161206_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_agent',
            field=models.NullBooleanField(),
        ),
    ]
