# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161213_0026'),
        ('account', '0002_auto_20161213_1835'),
    ]

    operations = [
    ]
