# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_validate_email'),
        ('account', '0007_coastalbucket_transaction'),
    ]

    operations = [
    ]
