# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_validate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='validateemail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.CharField(blank=True, choices=[('unconfirmed', 'unconfirmed'), ('sending', 'sending'), ('confirmed', 'confirmed')], default='unconfirmed', max_length=32),
        ),
    ]
