# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_merge_20161230_0143'),
        ('account', '0008_alter_validateemail_field'),
    ]

    operations = [
    ]
