# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 08:36
from __future__ import unicode_literals

from django.db import migrations


def init_coastal_bucket(apps, schema_editor):
    CoastalBucket = apps.get_model("account", "CoastalBucket")
    User = apps.get_model("auth", "User")

    for user in User.objects.all():
        if not hasattr(user, 'coastalbucket'):
            CoastalBucket.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20170103_2245'),
    ]

    operations = [
        migrations.RunPython(init_coastal_bucket),
    ]
