# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 05:57
from __future__ import unicode_literals

from django.db import migrations


def alter_username_lower(apps, schema_editor):
    User = apps.get_model("auth", "User")
    user_list = User.objects.all()
    for user in user_list:
        if user.username != user.username.lower():
            is_exist = User.objects.filter(username=user.username.lower())
            if is_exist:
                print('current user %s already exist lower format' % user.username)
            else:
                user.username = user.username.lower()
                user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_userprofile_client'),
    ]

    operations = [
        migrations.RunPython(alter_username_lower),
    ]
