# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_upper_to_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purpose',
            field=models.TextField(default=''),
        ),
    ]
