# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_invitecode'),
        ('account', '0016_userprofile_purpose'),
    ]

    operations = [
    ]
