# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0018_merge_20170212_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=32)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_invite_code', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invite_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='user',
        ),
        migrations.AddField(
            model_name='invitecode',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='invite_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
