# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_create_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
