# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 06:08
from __future__ import unicode_literals

from django.db import migrations


def update_first_name(apps, schema_editor):
    User = apps.get_model("auth", "User")
    user_list = User.objects.all()
    for user in user_list:
        if user.last_name and not user.first_name:
            user.first_name = user.last_name
            user.last_name = ''
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_allow_purpose_null_0214'),
    ]

    operations = [
        migrations.RunPython(update_first_name)
    ]
