# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_update_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
