# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 06:08
from __future__ import unicode_literals

from django.db import migrations


def recently_no_repeat(apps, schema_editor):
    User = apps.get_model("auth", "User")
    RecentlyViewed = apps.get_model('account', 'RecentlyViewed')
    user_list = User.objects.all()
    for user in user_list:
        repeat = []
        recently_views = list(user.recently_viewed.all().values_list('product_id', flat=True))
        for recently_view in recently_views:
            if recently_views.count(recently_view) > 1:
                repeat.append(recently_view)
        repeat = set(repeat)
        if repeat:
            for i in repeat:
                p = RecentlyViewed.objects.filter(product_id=i, user=user).order_by('-date_created')[1:]
                for p_i in p:
                    p_i.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0023_transaction_20170221_2328'),
    ]

    operations = [
        migrations.RunPython(recently_no_repeat)
    ]
