# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_recentlyviewed_no_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
