# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviterecord',
            name='referrer_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inviterecord',
            name='user_reward',
            field=models.BooleanField(default=False),
        ),
    ]
