# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 10:29
from __future__ import unicode_literals

from django.db import migrations


def update_invite_record(apps, schema_editor):
    InviteRecord = apps.get_model('account', 'InviteRecord')
    Transaction = apps.get_model('account', 'Transaction')

    reward_records = Transaction.objects.filter(note='invite_user').values_list('user_id', 'amount', 'date_created')
    user_reward_record = {}
    referrer_reward_record = {}
    for user_id, amount, date in reward_records:
        if amount == 35:
            user_reward_record[user_id] = date
        if amount == 10:
            referrer_reward_record[user_id] = date

    invite_records = InviteRecord.objects.all()
    for invite_record in invite_records:
        if invite_record.user_id in user_reward_record:
            invite_record.user_reward = user_reward_record[invite_record.user_id]
        if invite_record.referrer_id in referrer_reward_record:
            invite_record.referrer_reward = referrer_reward_record[invite_record.referrer_id]
        invite_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20170323_0329'),
    ]

    operations = [
    ]
