# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:04
from __future__ import unicode_literals

from django.db import migrations


def update_currency(apps, schema_editor):
    Currency = apps.get_model('currency', 'Currency')

    currency = (
        (1, '美元', 'USD', '$', 1),
        (2, '纽元', 'NZD', '$', 1),
        (3, '澳元', 'AUD', '$', 1),
        (4, '港币', 'HKD', '$', 1),
        (5, '加元', 'CAD', '$', 1),
        (6, '日元', 'JPY', '￥', 1),
        (7, '新元', 'SGD', 'S$', 1),
        (8, '瑞郎', 'CHF', 'CHF', 1),
        (9, '欧元', 'EUR', '€', 1),
        (10, '英镑', 'GBP', '￡', 1),
        (11, '人民币', 'CNY', '￥', 1)
    )

    for cid, name, code, symbol, rate in currency:
        Currency.objects.create(id=cid, name=name, code=code, symbol=symbol, rate=rate)


def reverse_update_currency(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")

    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_update_symbol'),
    ]

    operations = [
        migrations.RunPython(update_currency, reverse_update_currency),
    ]
