# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_add_currency_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='display',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
