# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0031_auto_20161224_0708'),
        ('rental', '0002_blackoutdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField()),
                ('notes', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_token', models.CharField(max_length=128)),
                ('payment_type', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(max_length=3)),
                ('guest_count', models.PositiveSmallIntegerField()),
                ('sub_total_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_orders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('w', 'Weekly'), ('m', 'Monthly')], max_length=1)),
                ('discount_rate', models.IntegerField(help_text='The unit is %. e.g. 60 means 60%')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.RentalOrder')),
            ],
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.RentalOrder'),
        ),
        migrations.AddField(
            model_name='approveevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.RentalOrder'),
        ),
    ]
