# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20161224_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
