# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20161225_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='rental_unit',
            field=models.CharField(choices=[('day', 'Day'), ('half-day', 'Half-Day'), ('hour', 'Hour')], default='day', max_length=32),
        ),
    ]
