# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_rentalorder_rental_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
    ]
