# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20170104_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('approved', 'Approved'), ('declined', 'Declined'), ('invalid', 'Invalid'), ('charge', 'Charge'), ('booked', 'Booked'), ('check-in', 'Check-In'), ('paid', 'Paid Host'), ('check-out', 'Check-out'), ('finished', 'Finished')], max_length=32),
        ),
    ]
