# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_field_timezone'),
        ('rental', '0006_auto_20170104_0525'),
    ]

    operations = [
    ]
