# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_merge_20170104_2226'),
        ('rental', '0007_rentalorder_status'),
    ]

    operations = [
    ]
