# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20170110_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaldaterange',
            name='product',
        ),
        migrations.AlterField(
            model_name='blackoutdate',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blackoutdate',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='RentalDateRange',
        ),
    ]
