# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20170110_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
