# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_update_blackout_date'),
        ('rental', '0011_auto_20170112_0041'),
    ]

    operations = [
    ]
