# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_remove_product_reported'),
        ('rental', '0013_merge_20170112_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOutDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
