# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 10:05
from __future__ import unicode_literals

from django.db import migrations


def correct_order_status(apps, schema_editor):
    RentalOrder = apps.get_model("rental", "RentalOrder")
    orders = RentalOrder.objects.all()
    for order in orders:
        if order.status == 'check_in':
            order.status = 'check-in'
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_rentaloutdate'),
    ]

    operations = [
        migrations.RunPython(correct_order_status)
    ]
