# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_correct_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='rental_unit',
            field=models.CharField(choices=[('day', 'Day'), ('half-day', 'Half-Day'), ('hour', 'Hour'), ('week', 'Week')], default='day', max_length=32),
        ),
    ]
